### ISSUE TITLE
had an error with the trims on tools

### ISSUE THREAD

**Issue by joanqwx** [dragon-forge/TrimsOnTools#5]
net.neoforged.fml.ModLoadingException: Loading errors encountered:
	- Trims on Tools (trims_on_tools) encountered an error while dispatching the net.neoforged.neoforge.event.BuildCreativeModeTabContentsEvent event

**Comment by joanqwx** [comment]
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-08-21 22:43:54
Description: Unexpected error

net.neoforged.fml.ModLoadingException: Loading errors encountered:
	- Trims on Tools (trims_on_tools) encountered an error while dispatching the net.neoforged.neoforge.event.BuildCreativeModeTabContentsEvent event
	  java.lang.NoSuchMethodError: 'net.neoforged.neoforge.common.util.MutableHashedLinkedMap net.neoforged.neoforge.event.BuildCreativeModeTabContentsEvent.getEntries()'

	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:181) ~[loader-4.0.23.jar%2398!/:4.0] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.lambda$postEvent$13(ModLoader.java:358) ~[loader-4.0.23.jar%2398!/:4.0] {}
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModList.forEachModInOrder(ModList.java:164) ~[loader-4.0.23.jar%2398!/:4.0] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.postEvent(ModLoader.java:358) ~[loader-4.0.23.jar%2398!/:4.0] {}
	at TRANSFORMER/neoforge@21.0.166/net.neoforged.neoforge.event.EventHooks.onCreativeModeTabBuildContents(EventHooks.java:1103) ~[neoforge-21.0.166-universal.jar%23333!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.item.CreativeModeTab.buildContents(CreativeModeTab.java:145) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.item.CreativeModeTabs.lambda$buildAllTabContents$48(CreativeModeTabs.java:2166) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:classloading,pl:accesstransformer:B}
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?] {}
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin}
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?] {}
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.item.CreativeModeTabs.buildAllTabContents(CreativeModeTabs.java:2166) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.item.CreativeModeTabs.tryRebuildTabContents(CreativeModeTabs.java:2177) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.tryRebuildTabContents(CreativeModeInventoryScreen.java:148) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:inventoryessentials.mixins.json:CreativeModeInventoryScreenAccessor from mod inventoryessentials,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.<init>(CreativeModeInventoryScreen.java:124) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:inventoryessentials.mixins.json:CreativeModeInventoryScreenAccessor from mod inventoryessentials,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.gui.screens.inventory.InventoryScreen.init(InventoryScreen.java:57) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.gui.screens.Screen.init(Screen.java:317) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.neoforge.mixins.json:ScreenAccessor from mod balm,pl:mixin:APP:konkrete.mixins.json:client.IMixinScreen from mod konkrete,pl:mixin:APP:nerb-common.mixins.json:ScreenMixin from mod nerb,pl:mixin:APP:journeymap.mixins.json:client.ScreenAccessor from mod journeymap,pl:mixin:APP:iceberg.mixins.json:ScreenMixin from mod iceberg,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.setScreen(Minecraft.java:1057) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.handleKeybinds(Minecraft.java:1974) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.tick(Minecraft.java:1837) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.runTick(Minecraft.java:1161) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.23.jar%2398!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.23.jar%2398!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.23.jar%2398!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.23.jar%2398!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23110!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23110!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23110!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23110!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23110!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23110!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23110!/:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:181) ~[loader-4.0.23.jar%2398!/:4.0] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.lambda$postEvent$13(ModLoader.java:358) ~[loader-4.0.23.jar%2398!/:4.0] {}
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModList.forEachModInOrder(ModList.java:164) ~[loader-4.0.23.jar%2398!/:4.0] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.postEvent(ModLoader.java:358) ~[loader-4.0.23.jar%2398!/:4.0] {}
	at TRANSFORMER/neoforge@21.0.166/net.neoforged.neoforge.event.EventHooks.onCreativeModeTabBuildContents(EventHooks.java:1103) ~[neoforge-21.0.166-universal.jar%23333!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.item.CreativeModeTab.buildContents(CreativeModeTab.java:145) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.item.CreativeModeTabs.lambda$buildAllTabContents$48(CreativeModeTabs.java:2166) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:classloading,pl:accesstransformer:B}
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?] {}
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin}
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?] {}
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.item.CreativeModeTabs.buildAllTabContents(CreativeModeTabs.java:2166) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.item.CreativeModeTabs.tryRebuildTabContents(CreativeModeTabs.java:2177) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.tryRebuildTabContents(CreativeModeInventoryScreen.java:148) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:inventoryessentials.mixins.json:CreativeModeInventoryScreenAccessor from mod inventoryessentials,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.<init>(CreativeModeInventoryScreen.java:124) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:inventoryessentials.mixins.json:CreativeModeInventoryScreenAccessor from mod inventoryessentials,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.gui.screens.inventory.InventoryScreen.init(InventoryScreen.java:57) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.gui.screens.Screen.init(Screen.java:317) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.neoforge.mixins.json:ScreenAccessor from mod balm,pl:mixin:APP:konkrete.mixins.json:client.IMixinScreen from mod konkrete,pl:mixin:APP:nerb-common.mixins.json:ScreenMixin from mod nerb,pl:mixin:APP:journeymap.mixins.json:client.ScreenAccessor from mod journeymap,pl:mixin:APP:iceberg.mixins.json:ScreenMixin from mod iceberg,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.setScreen(Minecraft.java:1057) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.handleKeybinds(Minecraft.java:1974) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
-- Uptime --
Details:
	JVM uptime: 63.676s
	Wall uptime: 45.871s
	High-res time: 60.306s
	Client ticks: 412 ticks / 20.600s
Stacktrace:
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.fillReport(Minecraft.java:2392) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.emergencySaveAndCrash(Minecraft.java:868) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.run(Minecraft.java:828) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21-20240613.152323-srg.jar%23332!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.23.jar%2398!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.23.jar%2398!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.23.jar%2398!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.23.jar%2398!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23110!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23110!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23110!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23110!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23110!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23110!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23110!/:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}


-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['_Butterflyk_'/19, l='ClientLevel', x=40.13, y=74.36, z=154.84]]
	Chunk stats: 961, 505
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,67,0), Section: (at 0,3,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1548 game time, 1548 day time
	Server brand: neoforge
	Server type: Integrated singleplayer server
	Tracked entity count: 207

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
REDACTED

-- System Details --
REDACTED
	Crash Report UUID: 059de57c-e5dc-4936-b772-9e0aba302c11
	FML: 4.0.23
	NeoForge: 21.0.166
```

**Comment by Zeitheron** [comment]
Fixed in 21.0.3.

**Comment by joanqwx** [comment]
where i can download 21.0.3?

**Comment by joanqwx** [comment]
can you add it on curseforge please?

**Comment by Zeitheron** [comment]
It's currently under review. I can't make it go faster.
Please wait for a few hours, or grab a version from [Modrinth](https://modrinth.com/mod/trims-on-tools/version/21.0.3)

**Comment by joanqwx** [comment]
thank u very much!
